name: longer_stories
description: Set Longer Stories on WhatsApp and Instagram

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.3.0
  permission_handler: ^3.2.2
  get_it: ^3.0.1
  provider: ^3.1.0
  thumbnails: ^1.0.1
  video_player: ^0.10.2+1
  chewie: ^0.9.8
  screen: ^0.0.5
  share_extend: ^1.0.9
  rflutter_alert: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
